/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UP2YOUSERVICE_H_RPCGEN
#define _UP2YOUSERVICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef int boolean;

struct date {
	int jour;
	int mois;
	int annee;
};
typedef struct date date;

struct adresse {
	int numero;
	char voie[100];
	int cp;
	char ville[45];
};
typedef struct adresse adresse;

struct donnee_bc {
	int numero;
	date date_exp;
	int crypto;
};
typedef struct donnee_bc donnee_bc;

struct client {
	int id;
	char nom[45];
	char prenom[45];
	struct donnee_bc donnee_bc;
	boolean rib;
	boolean pi;
	boolean fact_tel;
	adresse list_adresse[3];
};
typedef struct client client;

struct liste_clients {
	client liste[10];
	int nbClients;
};
typedef struct liste_clients liste_clients;

#define UP2US_PROG 0x23456789
#define UP2US_V_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  void * init_1(void *, CLIENT *);
extern  void * init_1_svc(void *, struct svc_req *);
#define GET_CLIENTS 2
extern  liste_clients * get_clients_1(void *, CLIENT *);
extern  liste_clients * get_clients_1_svc(void *, struct svc_req *);
#define GET_CLIENT 3
extern  client * get_client_1(int *, CLIENT *);
extern  client * get_client_1_svc(int *, struct svc_req *);
extern int up2us_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  void * init_1();
extern  void * init_1_svc();
#define GET_CLIENTS 2
extern  liste_clients * get_clients_1();
extern  liste_clients * get_clients_1_svc();
#define GET_CLIENT 3
extern  client * get_client_1();
extern  client * get_client_1_svc();
extern int up2us_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_boolean (XDR *, boolean*);
extern  bool_t xdr_date (XDR *, date*);
extern  bool_t xdr_adresse (XDR *, adresse*);
extern  bool_t xdr_donnee_bc (XDR *, donnee_bc*);
extern  bool_t xdr_client (XDR *, client*);
extern  bool_t xdr_liste_clients (XDR *, liste_clients*);

#else /* K&R C */
extern bool_t xdr_boolean ();
extern bool_t xdr_date ();
extern bool_t xdr_adresse ();
extern bool_t xdr_donnee_bc ();
extern bool_t xdr_client ();
extern bool_t xdr_liste_clients ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UP2YOUSERVICE_H_RPCGEN */
