/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2youService.h"

int g_nb_clients = 0;
client g_liste_clients[10];

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	g_liste_clients[0].id = 0;
	strcpy("Nadira", g_liste_clients[0].prenom);
	strcpy("Nadira", g_liste_clients[0].nom);
	g_liste_clients[0].donnee_bc.numero = 1215752192;
	g_liste_clients[0].donnee_bc.crypto = 100;
	g_liste_clients[0].donnee_bc.date_exp.jour = 1;
	g_liste_clients[0].donnee_bc.date_exp.mois = 1;
	g_liste_clients[0].donnee_bc.date_exp.annee = 2022;
	g_liste_clients[0].rib = 1;
	g_liste_clients[0].pi = 1;
	g_liste_clients[0].fact_tel = 1;
	g_liste_clients[0].list_adresse[0].numero = 1;
	strcpy("Rue du général", g_liste_clients[0].list_adresse[0].voie);
	g_liste_clients[0].list_adresse[0].cp = 29200;
	strcpy("Brest", g_liste_clients[0].list_adresse[0].ville);
	g_nb_clients++;
	return (void *) &result;
}

liste_clients *
get_clients_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_clients result;
	int i = 0;
	for(i; i<g_nb_clients; i++) {
		result.liste[i] = g_liste_clients[i];
	}
	result.nbClients = i;
	return &result;
}

client *
get_client_1_svc(int *argp, struct svc_req *rqstp)
{
	static client  result;

	result = g_liste_clients[*argp];

	return &result;
}
