/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"


void
test_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	historiqueCommande  *HistoCmds;
	date  hDate;

#ifndef	DEBUG
	clnt = clnt_create (host, TEST, LIBRAIRIE_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	hDate.jour = 18;
	hDate.mois = 03;
	hDate.annee = 2019;
	HistoCmds = historique_commande_1(&hDate, clnt);
	if (HistoCmds == (historiqueCommande *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Nombre Commandes : %d\n", HistoCmds->nbCommandes);
	int i;
	for (i = 0; i < HistoCmds->nbCommandes; i++) {
		printf("Commande : %d\n",i+1);
		printf("\tid : %ld\n", HistoCmds->listCommande[i].idLivre);
		printf("\tquantite : %d\n", HistoCmds->listCommande[i].quantite);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	test_1 (host);
exit (0);
}
