/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "test.h"

int nbCommandes;
commande listCommande[50]; 


void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	int i; 
	nbCommandes = 0;
	for (i = 0; i < 3; i++) {
		listCommande[i].idLivre = 2*(i+1);
		listCommande[i].quantite = 10*(i+1);
		listCommande[i].date.jour = 18;	
		listCommande[i].date.mois = 03;	
		listCommande[i].date.annee = 2019;	
		nbCommandes++;
	}

	return (void *) &result;
}

historiqueCommande *
historique_commande_1_svc(date *dateHisto, struct svc_req *rqstp)
{
	static historiqueCommande  result;
	result.nbCommandes = 0;
	int i;
	for (i = 0; i < nbCommandes; i++) {

		if ( (listCommande[i].date.jour == dateHisto->jour) && (listCommande[i].date.mois == dateHisto->mois) && (listCommande[i].date.annee == dateHisto->annee) ) {
			// On stock la vente courante dans la liste des ventes a retourner
			result.listCommande[result.nbCommandes] = listCommande[i];
			result.nbCommandes += 1;
		}
		// Seule l'annee est selectionée
		else if((listCommande[i].date.jour == -1) && (listCommande[i].date.mois == -1) && (listCommande[i].date.annee == dateHisto->annee)){
			// On stock la vente courante dans la liste des ventes a retourner
			result.listCommande[result.nbCommandes] = listCommande[i];
			result.nbCommandes += 1;
		}
	}


	return &result;
}
