/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct date {
	int jour;
	int mois;
	int annee;
};
typedef struct date date;

struct commande {
	long idLivre;
	int quantite;
	date date;
};
typedef struct commande commande;

struct historiqueCommande {
	commande listCommande[50];
	int nbCommandes;
};
typedef struct historiqueCommande historiqueCommande;

#define TEST 0x23456789
#define LIBRAIRIE_V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT 1
extern  void * init_1(void *, CLIENT *);
extern  void * init_1_svc(void *, struct svc_req *);
#define HISTORIQUE_COMMANDE 2
extern  historiqueCommande * historique_commande_1(date *, CLIENT *);
extern  historiqueCommande * historique_commande_1_svc(date *, struct svc_req *);
extern int test_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT 1
extern  void * init_1();
extern  void * init_1_svc();
#define HISTORIQUE_COMMANDE 2
extern  historiqueCommande * historique_commande_1();
extern  historiqueCommande * historique_commande_1_svc();
extern int test_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_date (XDR *, date*);
extern  bool_t xdr_commande (XDR *, commande*);
extern  bool_t xdr_historiqueCommande (XDR *, historiqueCommande*);

#else /* K&R C */
extern bool_t xdr_date ();
extern bool_t xdr_commande ();
extern bool_t xdr_historiqueCommande ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
