/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test.h"

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_commande (XDR *xdrs, commande *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->idLivre))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->quantite))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_historiqueCommande (XDR *xdrs, historiqueCommande *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->listCommande, 50,
		sizeof (commande), (xdrproc_t) xdr_commande))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbCommandes))
		 return FALSE;
	return TRUE;
}
