/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2youService.h"

client g_liste_clients[10];
int g_nb_clients;

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	g_liste_clients[0].id = 0;
	strcpy(g_liste_clients[0].prenom, "Nadira");
	strcpy(g_liste_clients[0].nom, "Dera");
	g_liste_clients[0].donnee_bc_client.numero = 121575219;
	g_liste_clients[0].donnee_bc_client.crypto = 100;
	g_liste_clients[0].donnee_bc_client.date_exp.jour = 1;
	g_liste_clients[0].donnee_bc_client.date_exp.mois = 1;
	g_liste_clients[0].donnee_bc_client.date_exp.annee = 2022;
	g_liste_clients[0].rib = 1;
	g_liste_clients[0].pi = 1;
	g_liste_clients[0].fact_tel = 1;
	g_liste_clients[0].list_adresse[0].numero = 1;
	strcpy(g_liste_clients[0].list_adresse[0].voie, "Rue");
	g_liste_clients[0].list_adresse[0].cp = 29200;
	strcpy(g_liste_clients[0].list_adresse[0].ville, "Brest");
	g_nb_clients++;

	return (void *) &result;
}

liste_clients *
get_clients_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_clients  result;
	int i = 0;
	for(i = 0; i < g_nb_clients; i++){
		result.liste[i] = g_liste_clients[i];
	}
	result.nbClients = i;
	return &result;
}

client *
get_client_1_svc(int *argp, struct svc_req *rqstp)
{
	static client  result;
	for(int i = 0; i<g_nb_clients; i++){
		if(g_liste_clients[i].id == *argp){
			result = g_liste_clients[i];
			break;
		}
	}

	return &result;
}
