/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMPTEUR_H_RPCGEN
#define _COMPTEUR_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define COMPTEURPROG ((rpc_uint)0x23456789)
#define COMPTEURVERS ((rpc_uint)1)

#ifdef __cplusplus
#define AJOUT ((rpc_uint)1)
extern "C" void * ajout_1(int *, CLIENT *);
extern "C" void * ajout_1_svc(int *, struct svc_req *);
#define LIRE ((rpc_uint)2)
extern "C" int * lire_1(void *, CLIENT *);
extern "C" int * lire_1_svc(void *, struct svc_req *);

#elif __STDC__
#define AJOUT ((rpc_uint)1)
extern  void * ajout_1(int *, CLIENT *);
extern  void * ajout_1_svc(int *, struct svc_req *);
#define LIRE ((rpc_uint)2)
extern  int * lire_1(void *, CLIENT *);
extern  int * lire_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define AJOUT ((rpc_uint)1)
extern  void * ajout_1();
extern  void * ajout_1_svc();
#define LIRE ((rpc_uint)2)
extern  int * lire_1();
extern  int * lire_1_svc();
#endif /* Old Style C */

#endif /* !_COMPTEUR_H_RPCGEN */
