/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "compteur.h"
int compteur = 0;
void *
ajout_1(argp, rqstp)
	int *argp;
	struct svc_req *rqstp;
{

	static char* result;

	compteur = compteur + *argp;
	printf("___________________________________________________________ \n");
	printf("ajout_1_svc : ajout du nombre : %d \n",*argp);

	return((void*) &result);
}

int *
lire_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{

	static int  result;

	result = compteur;
	printf("ajout_1_svc : nouveau compteur : %d \n",compteur) ;

	return(&result);
}
