/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATRICE_H_RPCGEN
#define _CALCULATRICE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params {
	long param1;
	long param2;
};
typedef struct params params;

#define CALC_PROG 0x20000001
#define CALC_VERSION_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define AJOUTER 1
extern  long * ajouter_1(params *, CLIENT *);
extern  long * ajouter_1_svc(params *, struct svc_req *);
#define SOUSTRAIRE 2
extern  long * soustraire_1(params *, CLIENT *);
extern  long * soustraire_1_svc(params *, struct svc_req *);
#define MULTIPLIER 3
extern  long * multiplier_1(params *, CLIENT *);
extern  long * multiplier_1_svc(params *, struct svc_req *);
#define MEMORISER_DERNIER_RESULTAT 4
extern  void * memoriser_dernier_resultat_1(int *, CLIENT *);
extern  void * memoriser_dernier_resultat_1_svc(int *, struct svc_req *);
#define EXTRAIRE_MEMOIRE 5
extern  long * extraire_memoire_1(int *, CLIENT *);
extern  long * extraire_memoire_1_svc(int *, struct svc_req *);
#define ALLUMER 6
extern  void * allumer_1(void *, CLIENT *);
extern  void * allumer_1_svc(void *, struct svc_req *);
extern int calc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AJOUTER 1
extern  long * ajouter_1();
extern  long * ajouter_1_svc();
#define SOUSTRAIRE 2
extern  long * soustraire_1();
extern  long * soustraire_1_svc();
#define MULTIPLIER 3
extern  long * multiplier_1();
extern  long * multiplier_1_svc();
#define MEMORISER_DERNIER_RESULTAT 4
extern  void * memoriser_dernier_resultat_1();
extern  void * memoriser_dernier_resultat_1_svc();
#define EXTRAIRE_MEMOIRE 5
extern  long * extraire_memoire_1();
extern  long * extraire_memoire_1_svc();
#define ALLUMER 6
extern  void * allumer_1();
extern  void * allumer_1_svc();
extern int calc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATRICE_H_RPCGEN */
