/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculatrice.h"

long dernier_result = 0.0;
long memoire[6] = { 0.0 };

long *
ajouter_1_svc(params *argp, struct svc_req *rqstp)
{
	printf("Ajout : param1 = %ld, param2 = %ld\n", argp->param1, argp->param2);
	static long  result;

	result = argp->param1 + argp->param2;
	dernier_result = result;

	return &result;
}

long *
soustraire_1_svc(params *argp, struct svc_req *rqstp)
{
	printf("Soust : param1 = %ld, param2 = %ld\n", argp->param1, argp->param2);
	static long  result;

	result = argp->param1 - argp->param2;
	dernier_result = result;

	return &result;
}

long *
multiplier_1_svc(params *argp, struct svc_req *rqstp)
{
	printf("Mult : param1 = %ld, param2 = %ld\n", argp->param1, argp->param2);
	static long  result;

	result = argp->param1 * argp->param2;
	dernier_result = result;

	return &result;
}

void *
memoriser_dernier_resultat_1_svc(int *argp, struct svc_req *rqstp)
{
	printf("Mémo : param = %d\n", *argp);
	static char * result;

	if( *argp > -1 && *argp < 6 ) {
		memoire[*argp] = dernier_result;
	}

	return (void *) &result;
}

long *
extraire_memoire_1_svc(int *argp, struct svc_req *rqstp)
{
	printf("Extr : param = %d\n", *argp);
	static long  result;

	if( *argp > -1 && *argp < 6 ) {
		result = memoire[*argp];
	}else{
		result = 0.0;
	}

	return &result;
}

void *
allumer_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("Allum\n");
	static char * result;

	return (void *) &result;
}
