/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2youService.h"

client g_client;

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	g_client.id = 0;
	strcpy("Nadira", g_client.prenom);
	strcpy("Nadira", g_client.nom);
	g_client.donnee_bc.numero = 1215752192;
	g_client.donnee_bc.crypto = 100;
	g_client.donnee_bc.date_exp.jour = 1;
	g_client.donnee_bc.date_exp.mois = 1;
	g_client.donnee_bc.date_exp.annee = 2022;
	g_client.rib = 1;
	g_client.pi = 1;
	g_client.fact_tel = 1;
	g_client.list_adresse[0].numero = 1;
	strcpy("Rue du général", g_client.list_adresse[0].voie);
	g_client.list_adresse[0].cp = 29200;
	strcpy("Brest", g_client.list_adresse[0].ville);

	return (void *) &result;
}

client *
get_client_1_svc(int *argp, struct svc_req *rqstp)
{
	static client  result;

	result = g_client;

	return &result;
}
