/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2youService.h"

#define NB_MAX_COMMANDES 10

client g_liste_clients[10];
int g_nb_clients;

commande g_liste_commandes[NB_MAX_COMMANDES];
int g_nb_commandes;

mobile g_liste_mobiles[10];
int g_nb_mobiles;

assurance g_liste_assurances[10];
int g_nb_assurances;

//Initialise les variable global du serveur
void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("Initialisation du serveur\n");
	
	static char * result;

	g_liste_clients[0].id = 0;
	strcpy(g_liste_clients[0].prenom, "Nadira");
	strcpy(g_liste_clients[0].nom, "DERA");
	g_liste_clients[0].donnee_bc_client.numero = 121575219;
	g_liste_clients[0].donnee_bc_client.crypto = 100;
	g_liste_clients[0].donnee_bc_client.date_exp.jour = 1;
	g_liste_clients[0].donnee_bc_client.date_exp.mois = 1;
	g_liste_clients[0].donnee_bc_client.date_exp.annee = 2022;
	g_liste_clients[0].rib = 1;
	g_liste_clients[0].pi = 1;
	g_liste_clients[0].fact_tel = 1;
	g_liste_clients[0].list_adresses.liste[0].numero = 1;
	strcpy(g_liste_clients[0].list_adresses.liste[0].voie, "Rue");
	g_liste_clients[0].list_adresses.liste[0].cp = 29200;
	strcpy(g_liste_clients[0].list_adresses.liste[0].ville, "Brest");
	g_liste_clients[0].list_adresses.nb_adresses = 1;
	
	g_liste_clients[1].id = 1;
	strcpy(g_liste_clients[1].prenom, "Jules");
	strcpy(g_liste_clients[1].nom, "FRÉRE");
	g_liste_clients[1].donnee_bc_client.numero = 121575219;
	g_liste_clients[1].donnee_bc_client.crypto = 100;
	g_liste_clients[1].donnee_bc_client.date_exp.jour = 1;
	g_liste_clients[1].donnee_bc_client.date_exp.mois = 1;
	g_liste_clients[1].donnee_bc_client.date_exp.annee = 2022;
	g_liste_clients[1].rib = 1;
	g_liste_clients[1].pi = 1;
	g_liste_clients[1].fact_tel = 1;
	g_liste_clients[1].list_adresses.liste[0].numero = 1;
	strcpy(g_liste_clients[1].list_adresses.liste[0].voie, "Rue");
	g_liste_clients[1].list_adresses.liste[0].cp = 29200;
	strcpy(g_liste_clients[1].list_adresses.liste[0].ville, "Brest");

	g_nb_clients=2;
	
	g_liste_mobiles[0].id=0;
	strcpy(g_liste_mobiles[0].nom, "Sumsong");
	g_liste_mobiles[0].prix_location = 49.99;
	g_liste_mobiles[0].prix_achat = 799.99;
	
	g_liste_mobiles[1].id=1;
	strcpy(g_liste_mobiles[1].nom, "Ifon");
	g_liste_mobiles[1].prix_location = 69.99;
	g_liste_mobiles[1].prix_achat = 1299.99;
	
	g_liste_mobiles[2].id=2;
	strcpy(g_liste_mobiles[2].nom, "Noucia");
	g_liste_mobiles[2].prix_location = 19.99;
	g_liste_mobiles[2].prix_achat = 120.0;
	
	g_nb_mobiles = 3;

	g_liste_assurances[0].id = 0;
	g_liste_assurances[0].prix = 90.0;
	strcpy(g_liste_assurances[0].description ,"Descr...");

	g_liste_assurances[1].id = 1;
	g_liste_assurances[1].prix = 19.9;
	strcpy(g_liste_assurances[1].description ,"Descr...");

	g_nb_assurances = 2;
	
	printf("Serveur initilisé\n");

	return (void *) &result;
}

//Renvoie la liste des clients
//retourne une structure liste_clients
liste_clients *
get_clients_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("Execution : get_clients(void)\n");
	
	static liste_clients result;
	int i = 0;
	for(i = 0; i < g_nb_clients; i++){
		result.liste[i] = g_liste_clients[i];
	}
	result.nb_clients = i;
	
	printf("Fin : get_clients(void)\n");
	
	return &result;
}

//Renvoie un certain client
//retourne un client ou NULL
client *
get_client_1_svc(int *argp, struct svc_req *rqstp)
{
	printf("Execution : get_client(%d)\n", *argp);
	
	static client  result;
	for(int i = 0; i<g_nb_clients; i++){
		if(g_liste_clients[i].id == *argp){
			result = g_liste_clients[i];
			break;
		}
	}
	
	printf("Fin : get_client(%d)\n", *argp);

	return &result;
}

//Verifie que le client existe et que tous ses documents sont valide
//retourne son index ou -1
int client_valide(int id){
	for(int i = 0; i<g_nb_clients; i++){
		if(g_liste_clients[i].id==id){
			if(g_liste_clients[i].rib && g_liste_clients[i].pi && g_liste_clients[i].fact_tel){
				return i;
			}
			return -1;
		}
	}
	return -1;
}

//Cree une commande relié a un certain client
//retourne l'id du client ou -1
int *
creer_commande_1_svc(int *argp, struct svc_req *rqstp)
{
	printf("Execution : creer_commande(%d)\n", *argp);
	
	static int  result;

	if(g_nb_commandes>=NB_MAX_COMMANDES || client_valide(*argp)==-1){
		result = -1;
	}else{
		g_liste_commandes[g_nb_commandes].id = g_nb_commandes;
		g_liste_commandes[g_nb_commandes].id_client = *argp;
		g_liste_commandes[g_nb_commandes].valide = 0;
		result = g_nb_commandes;
		g_nb_commandes++;
	}
	
	printf("Fin : creer_commande(%d)\n", *argp);

	return &result;
}

//Renvoie l'ensemble des mobiles
//retoune une structure liste_mobiles
liste_mobiles *
get_mobiles_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("Execution : get_mobiles(void)\n");	
	
	static liste_mobiles  result;
	int i = 0;
	for(i = 0; i < g_nb_mobiles; i++){
		result.liste[i] = g_liste_mobiles[i];
	}
	result.nb_mobiles = i;
	
	printf("Fin : get_mobiles(void)\n");
	
	return &result;
}

//Renvoie un certain mobile
//retourne le mobile ou NULL
mobile *
get_mobile_1_svc(int *argp, struct svc_req *rqstp)
{
	printf("Execution : get_mobile(%d)\n", *argp);

	static mobile  result;

	for(int i = 0; i < g_nb_mobiles; i++){
		if(g_liste_mobiles[i].id==*argp){
			result = g_liste_mobiles[i];
			break;
		}
	}

	printf("Fin : get_mobile(%d)\n", *argp);

	return &result;
}

//Verifie qu'un mobile existe
//retourne son index ou -1
int mobile_exist(int id){
	for(int i = 0; i<g_nb_mobiles; i++){
		if(g_liste_mobiles[i].id==id){
			return i;
		}
	}
	return -1;
}

//Verifie qu'une commande existe
//retourne son index ou -1
int commande_exist(int id){
	for(int i = 0; i < g_nb_commandes; i++){
		if(g_liste_commandes[i].id==id){
			return i;
		}
	}
	return -1;
}

//Modifie le mobile selectionné pour une certaine commande
//retourne 1 ou 0
boolean *
set_mobile_1_svc(params_set_mobile *argp, struct svc_req *rqstp)
{
	printf("Execution : set_mobile({%d, param_mobile})\n", argp->id_commande);

	static boolean  result = 0;
	
	int index_commande = commande_exist(argp->id_commande);

	if(mobile_exist(argp->param_mobile.id_mobile)==-1 || index_commande==-1){
		return &result;
	}

	g_liste_commandes[index_commande].mobile = argp->param_mobile;
	result = 1;
	
	printf("Execution : set_mobile({%d, param_mobile})\n", argp->id_commande);

	return &result;
}

//Renvoie la liste des assurances
liste_assurances *
get_assurances_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_assurances  result;

	for(int i = 0; i < g_nb_assurances; i++){
		result.liste[i] = g_liste_assurances[i];
	}

	result.nb_assurances = g_nb_assurances;

	return &result;
}

assurance *
get_assurance_1_svc(int *argp, struct svc_req *rqstp)
{
	static assurance  result;

	for(int i = 0; i < g_nb_assurances; i++){
		if(g_liste_assurances[i].id==*argp){
			result = g_liste_assurances[i];
			break;
		}
	}

	return &result;
}

boolean *
set_assurance_1_svc(params_set_assurance *argp, struct svc_req *rqstp)
{
	static boolean  result;

	int index_commande = commande_exist(argp->id_commande);

	if(index_commande==-1 || assurances_exist(argp->id_assurances)){
		result = 0;
		return &result;
	}

	g_liste_commandes[index_commande].id_assurance = argp->id_assurances;
	result = 1;

	return &result;
}



boolean *
set_adresse_livraison_1_svc(params_set_adresse *argp, struct svc_req *rqstp)
{
	static boolean  result;

	int index_commande = commande_exist(argp->id_commande);
	if(index_commande==-1){
		result = 0;
		return &result;
	}

	int index_client = client_valide(g_liste_commandes[index_commande].id_client);
	if(index_client==-1){
		result = 0;
		return &result;
	}

	if(argp->index_adresse_client<0 || g_liste_clients[index_client].list_adresses.nb_adresses<argp->index_adresse_client){
		result = 0;
		return &result;
	}

	g_liste_commandes[index_commande].index_adresse_client = argp->index_adress_client;
	result = 1;

	return &result;
}

liste_commandes *
get_commandes_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_commandes  result;

	for(int i = 0; i < g_nb_commandes; i++){
		result.liste[i] = g_liste_commandes[i];
	}
	result.nb_commandes = g_nb_commandes;

	return &result;
}

commande *
get_commande_1_svc(int *argp, struct svc_req *rqstp)
{
	static commande  result;

	for(int i = 0; i < g_nb_commandes; i++){
		if(g_liste_commandes[i].id == *argp){
			result = g_liste_commandes[i];
			break;
		}
	}

	return &result;
}

boolean *
valide_commande_1_svc(int *argp, struct svc_req *rqstp)
{
	static boolean  result;

	int index_commande = commande_exist(*argp);

	if(index_commande==-1){
		result = 0;
		return &result;
	}

	g_liste_commandes[index_commande].valide = 1;
	result = 1;

	return &result;
}

boolean *
set_date_livraison_1_svc(params_set_dl *argp, struct svc_req *rqstp)
{
	static boolean  result;

	int index_commande = commande_exist(argp->id_commande);
	if(index_commande==-1 || !g_liste_commandes[index_commande].valide){
		result = 0;
		return &result;
	}

	g_liste_commandes[index_commande].date_livraison = argp->dl;

	return &result;
}
