/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "up2youService.h"

bool_t
xdr_boolean (XDR *xdrs, boolean *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_date (XDR *xdrs, date *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->jour))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mois))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->annee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_adresse (XDR *xdrs, adresse *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numero))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->voie, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->cp))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->ville, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_donnee_bc (XDR *xdrs, donnee_bc *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numero))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_exp))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->crypto))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste_adresses (XDR *xdrs, liste_adresses *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->liste, 3,
		sizeof (adresse), (xdrproc_t) xdr_adresse))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_adresses))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_donnee_bc (xdrs, &objp->donnee_bc_client))
		 return FALSE;
	 if (!xdr_boolean (xdrs, &objp->rib))
		 return FALSE;
	 if (!xdr_boolean (xdrs, &objp->pi))
		 return FALSE;
	 if (!xdr_boolean (xdrs, &objp->fact_tel))
		 return FALSE;
	 if (!xdr_liste_adresses (xdrs, &objp->list_adresses))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mobile (XDR *xdrs, mobile *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix_location))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix_achat))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_e_type (XDR *xdrs, e_type *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_type (XDR *xdrs, type *objp)
{
	register int32_t *buf;

	 if (!xdr_e_type (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_e_couleur (XDR *xdrs, e_couleur *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_couleur (XDR *xdrs, couleur *objp)
{
	register int32_t *buf;

	 if (!xdr_e_couleur (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_e_connect (XDR *xdrs, e_connect *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_connectivite (XDR *xdrs, connectivite *objp)
{
	register int32_t *buf;

	 if (!xdr_e_connect (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_e_memoire (XDR *xdrs, e_memoire *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_memoire (XDR *xdrs, memoire *objp)
{
	register int32_t *buf;

	 if (!xdr_e_memoire (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params_mobile (XDR *xdrs, params_mobile *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_mobile))
		 return FALSE;
	 if (!xdr_type (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_couleur (xdrs, &objp->couleur))
		 return FALSE;
	 if (!xdr_connectivite (xdrs, &objp->connectivite))
		 return FALSE;
	 if (!xdr_memoire (xdrs, &objp->memoire))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_assurance (XDR *xdrs, assurance *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->description, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_commande (XDR *xdrs, commande *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_client))
		 return FALSE;
	 if (!xdr_params_mobile (xdrs, &objp->mobile))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_assurance))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index_adresse_client))
		 return FALSE;
	 if (!xdr_boolean (xdrs, &objp->valide))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->date_livraison))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste_mobiles (XDR *xdrs, liste_mobiles *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->liste, 10,
		sizeof (mobile), (xdrproc_t) xdr_mobile))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_mobiles))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste_clients (XDR *xdrs, liste_clients *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->liste, 10,
		sizeof (client), (xdrproc_t) xdr_client))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_clients))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste_assurances (XDR *xdrs, liste_assurances *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->liste, 10,
		sizeof (assurance), (xdrproc_t) xdr_assurance))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_assurances))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_liste_commandes (XDR *xdrs, liste_commandes *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->liste, 10,
		sizeof (commande), (xdrproc_t) xdr_commande))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_commandes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params_set_mobile (XDR *xdrs, params_set_mobile *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_commande))
		 return FALSE;
	 if (!xdr_params_mobile (xdrs, &objp->param_mobile))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params_set_assurance (XDR *xdrs, params_set_assurance *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_commande))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_assurances))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params_set_adresse (XDR *xdrs, params_set_adresse *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_commande))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->index_adresse_client))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_params_set_dl (XDR *xdrs, params_set_dl *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id_commande))
		 return FALSE;
	 if (!xdr_date (xdrs, &objp->dl))
		 return FALSE;
	return TRUE;
}
