/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2youService.h"

const char c_enum_type[10][10] = {"Achat", "Location"};
const char c_enum_couleur[10][10] = {"Rouge", "Vert", "Bleu"};
const char c_enum_connect[10][10] = {"4G", "5G"};
const char c_enum_memoire[10][10] = {"128go", "256go", "512go"};

//Affiche les données d'un client
void afficher_client(const client * c){
	printf("\tId : %d\n", c->id);
    printf("\tNom : %s\n", c->nom);
    printf("\tPrenom : %s\n", c->prenom);
    
	printf("\tDonnees bancaires :\n");
    printf("\t\tNumero : %d\n", c->donnee_bc_client.numero);
    printf("\t\tDate : %02d/%02d/%02d\n", c->donnee_bc_client.date_exp.jour, c->donnee_bc_client.date_exp.mois, c->donnee_bc_client.date_exp.annee);
    printf("\t\tCrypto : %d\n", c->donnee_bc_client.crypto);
    
    printf("\tRib : %s\n", c->rib ? "Valide" : "Non valide");
    printf("\tPi : %s\n", c->pi ? "Valide" : "Non valide");
    printf("\tFact_tel : %s\n", c->fact_tel ? "Valide" : "Non valide");
    
    printf("\tListe adresses :\n");
    for (int i = 0; i<c->list_adresses.nb_adresses; i ++) {
        printf("\t\tAdresse %d : \n", i);
        printf("\t\t\t%d %s \n\t\t\t%d %s\n", c->list_adresses.liste[i].numero, c->list_adresses.liste[i].voie, c->list_adresses.liste[i].cp, c->list_adresses.liste[i].ville);
    }
	return;
}

//Affiche les données d'un enum
void afficher_enum(const char t_enum[10][10]){
	for(int i = 0; i < 10; i++){
		if(strcmp(t_enum[i],"")==0){
			break;
		}
		printf("%s, ", t_enum[i]);
	}
	printf("\n");
}

//Affiche les données d'un mobile
void afficher_mobile(const mobile * m){
	printf("\tId : %d\n", m->id);
	printf("\tNom : %s\n", m->nom);
	printf("\tPrix location : %.2f\n", m->prix_location);
	printf("\tPrix achat : %.2f\n", m->prix_achat);
	printf("\tType : ");
	afficher_enum(c_enum_type);
	printf("\tCouleur : ");
	afficher_enum(c_enum_couleur);
	printf("\tConnectivité : ");
	afficher_enum(c_enum_connect);
	printf("\tMémoire : ");
	afficher_enum(c_enum_memoire);
	return;
}

void afficher_assurance(const assurance * a){
	printf("\tId : %d\n", a->id);
	printf("\tDescription : %s\n", a->description);
	printf("\tPrix : %d\n", a->prix);
}

void afficher_commande(const commande * c){
	printf("\tId : %d\n", c->id);
	printf("\tId client : %d\n", c->id_client);
	printf("\tParamamètre mobile :\n");
	printf("\t\tId : %d \n", c->mobile.id_mobile);
	printf("\t\tCouleur : %s\n", c_enum_couleur[c->mobile.couleur]);
	printf("\t\t%s\n", c_enum_type[c->mobile.type]);
	printf("\t\tCommectivité : %s\n", c_enum_connect[c->mobile.connectivite]);
	printf("\t\tMémoire : %s\n", c_enum_memoire[c->mobile.memoire]);
	printf("\tId assurance : %d\n", c->id_assurance);
	printf("\tDate de livraison : %02d/%02d/%02d\n", c->date_livraison.jour, c->date_livraison.mois, c->date_livraison.annee);
	printf("\tValide : %s\n", c->valide ? "Valide" : "Non valide");

}

void
up2us_prog_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	liste_clients  *result_2;
	char *get_clients_1_arg;
	client  *result_3;
	int  get_client_1_arg;
	int  *result_4;
	int  creer_commande_1_arg;
	liste_mobiles  *result_5;
	char *get_mobiles_1_arg;
	mobile  *result_6;
	int  get_mobile_1_arg;
	boolean  *result_7;
	params_set_mobile  set_mobile_1_arg;
	liste_assurances  *result_8;
	char *get_assurances_1_arg;
	assurance  *result_9;
	int  get_assurance_1_arg;
	boolean  *result_10;
	params_set_assurance  set_assurance_1_arg;
	boolean  *result_11;
	params_set_adresse  set_adresse_livraison_1_arg;
	boolean  *result_12;
	int  valide_commande_1_arg;
	boolean  *result_13;
	params_set_dl  set_date_livraison_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, UP2US_PROG, UP2US_V_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Serveur initialisé\n");
	
	printf("-----------------------------------------------\n");
	
	result_2 = get_clients_1((void*)&get_clients_1_arg, clnt);
	if (result_2 == (liste_clients *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Liste clients :\n");
	for(int i = 0; i<result_2->nb_clients; i++){
		printf("\t%d : %s %s\n", result_2->liste[i].id, result_2->liste[i].nom, result_2->liste[i].prenom);
	}
	
	printf("-----------------------------------------------\n");
	
	get_client_1_arg = 0;
	printf("Afficher client : 0\n");

	result_3 = get_client_1(&get_client_1_arg, clnt);
	if (result_3 == (client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	afficher_client(result_3);
	
	printf("-----------------------------------------------\n");
	
	creer_commande_1_arg = 0;
	printf("Crèation d'une commande pour client 0\n");
	result_4 = creer_commande_1(&creer_commande_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%s\n", (*result_4)==-1 ? "Il n'y a plus de place" : "Création réussi");
	
	printf("-----------------------------------------------\n");

	result_5 = get_mobiles_1((void*)&get_mobiles_1_arg, clnt);
	if (result_5 == (liste_mobiles *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Liste mobiles :\n");
	for(int j = 0; j < result_5->nb_mobiles; j++){
		printf("\t%d : %s\n", result_5->liste[j].id, result_5->liste[j].nom);
	}
	
	printf("-----------------------------------------------\n");

	printf("Afficher mobile : 0\n");
	get_mobile_1_arg = 0;
	result_6 = get_mobile_1(&get_mobile_1_arg, clnt);
	if (result_6 == (mobile *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	afficher_mobile(result_6);
	
	printf("-----------------------------------------------\n");

	set_mobile_1_arg.id_commande = *result_4;
	set_mobile_1_arg.param_mobile.connectivite = G5;
	set_mobile_1_arg.param_mobile.couleur = VERT;
	set_mobile_1_arg.param_mobile.id_mobile = 0;
	set_mobile_1_arg.param_mobile.memoire = GO512;
	set_mobile_1_arg.param_mobile.type = LOCATION;

	result_7 = set_mobile_1(&set_mobile_1_arg, clnt);
	if (result_7 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%s\n",*result_7 ? "Paramètre mobile enregistré" : "L'enregitrement des paramètre n'a pas pu avoir lieu");
	
	printf("-----------------------------------------------\n");
	result_8 = get_assurances_1((void*)&get_assurances_1_arg, clnt);
	if (result_8 == (liste_assurances *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Liste des assurances : \n");
	for(int j = 0; j<result_8->nb_assurances; j++){
		printf("\t%d : %f\n",result_8->liste[j]);
	}

	printf("-----------------------------------------------\n");
	get_assurance_1_arg = 0;
	result_9 = get_assurance_1(&get_assurance_1_arg, clnt);
	if (result_9 == (assurance *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Assurance id : 0\n");
	afficher_assurance(result_9);

	printf("-----------------------------------------------\n");
	set_assurance_1_arg.id_commande = 0;
	set_assurance_1_arg.id_assurances = 0;
	result_10 = set_assurance_1(&set_assurance_1_arg, clnt);
	if (result_10 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Assurance enregistré pour la commande 0\n");
	printf("-----------------------------------------------\n");
	set_adresse_livraison_1_arg.id_commande = 0;
	set_adresse_livraison_1_arg.index_adresse_client = 0;
	result_11 = set_adresse_livraison_1(&set_adresse_livraison_1_arg, clnt);
	if (result_11 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Adresse de livraison bien enregistré\n");
	printf("-----------------------------------------------\n");

	valide_commande_1_arg = 0;
	result_12 = valide_commande_1(&valide_commande_1_arg, clnt);
	if (result_12 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Commande validé");
	printf("-----------------------------------------------\n");
	
	set_date_livraison_1_arg.id_commande = 0;
	set_date_livraison_1_arg.dl.annee = 2021;
	set_date_livraison_1_arg.dl.jour = 1;
	set_date_livraison_1_arg.dl.mois = 4;

	result_13 = set_date_livraison_1(&set_date_livraison_1_arg, clnt);
	if (result_13 == (boolean *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Date de livraison bien enregistré\n");
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	up2us_prog_1 (host);
exit (0);
}
