/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "up2youService.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
up2us_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int get_client_1_arg;
		int creer_commande_1_arg;
		int get_mobile_1_arg;
		params_set_mobile set_mobile_1_arg;
		int get_assurance_1_arg;
		params_set_assurance set_assurance_1_arg;
		params_set_adresse set_adresse_livraison_1_arg;
		int valide_commande_1_arg;
		params_set_dl set_date_livraison_1_arg;
		int get_commande_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) init_1_svc;
		break;

	case GET_CLIENTS:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_liste_clients;
		local = (char *(*)(char *, struct svc_req *)) get_clients_1_svc;
		break;

	case GET_CLIENT:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_client;
		local = (char *(*)(char *, struct svc_req *)) get_client_1_svc;
		break;

	case CREER_COMMANDE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) creer_commande_1_svc;
		break;

	case GET_MOBILES:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_liste_mobiles;
		local = (char *(*)(char *, struct svc_req *)) get_mobiles_1_svc;
		break;

	case GET_MOBILE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_mobile;
		local = (char *(*)(char *, struct svc_req *)) get_mobile_1_svc;
		break;

	case SET_MOBILE:
		_xdr_argument = (xdrproc_t) xdr_params_set_mobile;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) set_mobile_1_svc;
		break;

	case GET_ASSURANCES:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_liste_assurances;
		local = (char *(*)(char *, struct svc_req *)) get_assurances_1_svc;
		break;

	case GET_ASSURANCE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_assurance;
		local = (char *(*)(char *, struct svc_req *)) get_assurance_1_svc;
		break;

	case SET_ASSURANCE:
		_xdr_argument = (xdrproc_t) xdr_params_set_assurance;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) set_assurance_1_svc;
		break;

	case SET_ADRESSE_LIVRAISON:
		_xdr_argument = (xdrproc_t) xdr_params_set_adresse;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) set_adresse_livraison_1_svc;
		break;

	case VALIDE_COMMANDE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) valide_commande_1_svc;
		break;

	case SET_DATE_LIVRAISON:
		_xdr_argument = (xdrproc_t) xdr_params_set_dl;
		_xdr_result = (xdrproc_t) xdr_boolean;
		local = (char *(*)(char *, struct svc_req *)) set_date_livraison_1_svc;
		break;

	case GET_COMMANDE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_commande;
		local = (char *(*)(char *, struct svc_req *)) get_commande_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (UP2US_PROG, UP2US_V_1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, UP2US_PROG, UP2US_V_1, up2us_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (UP2US_PROG, UP2US_V_1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, UP2US_PROG, UP2US_V_1, up2us_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (UP2US_PROG, UP2US_V_1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
