/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "geometrie.h"

int *
surface_rectangle_1_svc(rectangle *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Execution surface_rectangle_1_svc\n"); 
	result = (argp->p2.x-argp->p1.x)*(argp->p1.y-argp->p2.y);

	return &result;
}

rectangle *
creer_rectangle_1_svc(coordonnees *argp, struct svc_req *rqstp)
{
	static rectangle  result;
	printf("Execution creer_rectangle_1_svc\n");
	result.p1.x = argp->x1;
	result.p1.y = argp->y1;
	result.p2.x = argp->x2;
	result.p2.y = argp->y2;
	
	return &result;
}

booleen *
inclus_1_svc(param_inclus *argp, struct svc_req *rqstp)
{
	static booleen  result;
	printf("Execution inclus_1_svc\n");

	result = ( argp->rect.p1.x <= argp->p.x && argp->p.x <= argp->rect.p2.x ) && ( argp->rect.p1.y >= argp->p.y && argp->p.y >= argp->rect.p2.y);

	return &result;
}
