/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "geometrie.h"


void
geom_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	rectangle  surface_rectangle_1_arg;
	rectangle  *result_2;
	coordonnees  creer_rectangle_1_arg;
	booleen  *result_3;
	param_inclus  inclus_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, GEOM_PROG, GEOM_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	creer_rectangle_1_arg.x1 = 0;
	creer_rectangle_1_arg.y1 = 2;
	creer_rectangle_1_arg.x2 = 3;
	creer_rectangle_1_arg.y2 = 0;

	result_2 = creer_rectangle_1(&creer_rectangle_1_arg, clnt);
	if (result_2 == (rectangle *) NULL) {
		clnt_perror (clnt, "call failed : creer_rectangle_1");
	}
	
	printf("rectangle créé : p1 (%d, %d) p2(%d, %d)\n", result_2->p1.x, result_2->p1.y, result_2->p2.x, result_2->p2.y);
	
	result_1 = surface_rectangle_1(result_2, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed : surface_rectangle_1");
	}
	
	printf("Surface du rectangle : %d\n", *result_1);
	
	inclus_1_arg.rect = *result_2;
	inclus_1_arg.p.x = 1;
	inclus_1_arg.p.y = 1;
	
	result_3 = inclus_1(&inclus_1_arg, clnt);
	if (result_3 == (booleen *) NULL) {
		clnt_perror (clnt, "call failed : inclus_1");
	}
	
	printf("Le point (1,1) est compris dans le rectangle ? %d\n", (int)*result_3);
	
	inclus_1_arg.p.x = 6;
	inclus_1_arg.p.y = 6;
	
	result_3 = inclus_1(&inclus_1_arg, clnt);
	if (result_3 == (booleen *) NULL) {
		clnt_perror (clnt, "call failed : inclus_1");
	}
	
	printf("Le point (6,6) est compris dans le rectangle ? %d\n", (int)*result_3);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	geom_prog_1 (host);
exit (0);
}
