/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "up2youService.h"
#include <sys/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <netdb.h>
#include <signal.h>
#include <sys/ttycom.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <syslog.h>

#ifdef __STDC__
#define SIG_PF void(*)(int)
#endif

#ifdef DEBUG
#define RPC_SVC_FG
#endif

#define _RPCSVC_CLOSEDOWN 120
static int _rpcpmstart;		/* Started by a port monitor ? */
static int _rpcfdtype;		/* Whether Stream or Datagram ? */
static int _rpcsvcdirty;	/* Still serving ? */

static
void _msgout(msg)
	char *msg;
{
#ifdef RPC_SVC_FG
	if (_rpcpmstart)
		syslog(LOG_ERR, "%s", msg);
	else
		(void) fprintf(stderr, "%s\n", msg);
#else
	syslog(LOG_ERR, "%s", msg);
#endif
}

static void
closedown()
{
	if (_rpcsvcdirty == 0) {
		extern fd_set svc_fdset;
		static int size;
		int i, openfd;

		if (_rpcfdtype == SOCK_DGRAM)
			exit(0);
		if (size == 0) {
			size = getdtablesize();
		}
		for (i = 0, openfd = 0; i < size && openfd < 2; i++)
			if (FD_ISSET(i, &svc_fdset))
				openfd++;
		if (openfd <= (_rpcpmstart?0:1))
			exit(0);
	}
	(void) alarm(_RPCSVC_CLOSEDOWN);
}

static void
up2us_prog_1(rqstp, transp)
	struct svc_req *rqstp;
	SVCXPRT *transp;
{
	union {
		int get_client_1_arg;
		int creer_commande_1_arg;
		int get_mobile_1_arg;
		params_set_mobile set_mobile_1_arg;
		int get_assurance_1_arg;
		params_set_assurance set_assurance_1_arg;
		params_set_adresse set_adresse_livraison_1_arg;
		int get_commande_1_arg;
		int valide_commande_1_arg;
		params_set_dl set_date_livraison_1_arg;
	} argument;
	char *result;
	bool_t (*xdr_argument)(), (*xdr_result)();
	char *(*local)();

	_rpcsvcdirty = 1;
	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply(transp, (xdrproc_t) xdr_void, (char *)NULL);
		_rpcsvcdirty = 0;
		return;

	case INIT:
		xdr_argument = xdr_void;
		xdr_result = xdr_void;
		local = (char *(*)()) init_1_svc;
		break;

	case GET_CLIENTS:
		xdr_argument = xdr_void;
		xdr_result = xdr_liste_clients;
		local = (char *(*)()) get_clients_1_svc;
		break;

	case GET_CLIENT:
		xdr_argument = xdr_int;
		xdr_result = xdr_client;
		local = (char *(*)()) get_client_1_svc;
		break;

	case CREER_COMMANDE:
		xdr_argument = xdr_int;
		xdr_result = xdr_int;
		local = (char *(*)()) creer_commande_1_svc;
		break;

	case GET_MOBILES:
		xdr_argument = xdr_void;
		xdr_result = xdr_liste_mobiles;
		local = (char *(*)()) get_mobiles_1_svc;
		break;

	case GET_MOBILE:
		xdr_argument = xdr_int;
		xdr_result = xdr_mobile;
		local = (char *(*)()) get_mobile_1_svc;
		break;

	case SET_MOBILE:
		xdr_argument = xdr_params_set_mobile;
		xdr_result = xdr_boolean;
		local = (char *(*)()) set_mobile_1_svc;
		break;

	case GET_ASSURANCES:
		xdr_argument = xdr_void;
		xdr_result = xdr_liste_assurances;
		local = (char *(*)()) get_assurances_1_svc;
		break;

	case GET_ASSURANCE:
		xdr_argument = xdr_int;
		xdr_result = xdr_assurance;
		local = (char *(*)()) get_assurance_1_svc;
		break;

	case SET_ASSURANCE:
		xdr_argument = xdr_params_set_assurance;
		xdr_result = xdr_boolean;
		local = (char *(*)()) set_assurance_1_svc;
		break;

	case SET_ADRESSE_LIVRAISON:
		xdr_argument = xdr_params_set_adresse;
		xdr_result = xdr_boolean;
		local = (char *(*)()) set_adresse_livraison_1_svc;
		break;

	case GET_COMMANDES:
		xdr_argument = xdr_void;
		xdr_result = xdr_liste_commandes;
		local = (char *(*)()) get_commandes_1_svc;
		break;

	case GET_COMMANDE:
		xdr_argument = xdr_int;
		xdr_result = xdr_commande;
		local = (char *(*)()) get_commande_1_svc;
		break;

	case VALIDE_COMMANDE:
		xdr_argument = xdr_int;
		xdr_result = xdr_boolean;
		local = (char *(*)()) valide_commande_1_svc;
		break;

	case SET_DATE_LIVRAISON:
		xdr_argument = xdr_params_set_dl;
		xdr_result = xdr_boolean;
		local = (char *(*)()) set_date_livraison_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		_rpcsvcdirty = 0;
		return;
	}
	(void) memset((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs(transp, xdr_argument, (caddr_t) &argument)) {
		svcerr_decode(transp);
		_rpcsvcdirty = 0;
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) xdr_result, result)) {
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, xdr_argument, (caddr_t) &argument)) {
		_msgout("unable to free arguments");
		exit(1);
	}
	_rpcsvcdirty = 0;
	return;
}



int
main(argc, argv)
int argc;
char *argv[];
{
	SVCXPRT *transp = NULL;
	int sock;
	int proto = 0;
	struct sockaddr_in saddr;
	int asize = sizeof (saddr);

	if (getsockname(0, (struct sockaddr *)&saddr, &asize) == 0) {
		int ssize = sizeof (int);

		if (saddr.sin_family != AF_INET)
			exit(1);
		if (getsockopt(0, SOL_SOCKET, SO_TYPE,
				(char *)&_rpcfdtype, &ssize) == -1)
			exit(1);
		sock = 0;
		_rpcpmstart = 1;
		proto = 0;
		openlog("up2youService", LOG_PID, LOG_DAEMON);
	} else {
#ifndef RPC_SVC_FG
		int size;
		int pid, i;

		pid = fork();
		if (pid < 0) {
			perror("cannot fork");
			exit(1);
		}
		if (pid)
			exit(0);
		size = getdtablesize();
		for (i = 0; i < size; i++)
			(void) close(i);
		i = open("/dev/console", 2);
		(void) dup2(i, 1);
		(void) dup2(i, 2);
		i = open("/dev/tty", 2);
		if (i >= 0) {
			(void) ioctl(i, TIOCNOTTY, (char *)NULL);
			(void) close(i);
		}
		openlog("up2youService", LOG_PID, LOG_DAEMON);
#endif
		sock = RPC_ANYSOCK;
		(void) pmap_unset(UP2US_PROG, UP2US_V_1);
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_DGRAM)) {
		transp = svcudp_create(sock);
		if (transp == NULL) {
			_msgout("cannot create udp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_UDP;
		if (!svc_register(transp, UP2US_PROG, UP2US_V_1, up2us_prog_1, proto)) {
			_msgout("unable to register (UP2US_PROG, UP2US_V_1, udp).");
			exit(1);
		}
	}

	if ((_rpcfdtype == 0) || (_rpcfdtype == SOCK_STREAM)) {
		if (_rpcpmstart)
			transp = svcfd_create(sock, 0, 0);
		else
			transp = svctcp_create(sock, 0, 0);
		if (transp == NULL) {
			_msgout("cannot create tcp service.");
			exit(1);
		}
		if (!_rpcpmstart)
			proto = IPPROTO_TCP;
		if (!svc_register(transp, UP2US_PROG, UP2US_V_1, up2us_prog_1, proto)) {
			_msgout("unable to register (UP2US_PROG, UP2US_V_1, tcp).");
			exit(1);
		}
	}

	if (transp == (SVCXPRT *)NULL) {
		_msgout("could not create a handle");
		exit(1);
	}
	if (_rpcpmstart) {
		(void) signal(SIGALRM, (void(*)()) closedown);
		(void) alarm(_RPCSVC_CLOSEDOWN);
	}
	svc_run();
	_msgout("svc_run returned");
	exit(1);
	/* NOTREACHED */
}
