/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "up2youService.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
init_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, INIT, xdr_void, argp, xdr_void, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return ((void *)&clnt_res);
}

liste_clients *
get_clients_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static liste_clients clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_CLIENTS, xdr_void, argp, xdr_liste_clients, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

client *
get_client_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static client clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_CLIENT, xdr_int, argp, xdr_client, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
creer_commande_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CREER_COMMANDE, xdr_int, argp, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

liste_mobiles *
get_mobiles_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static liste_mobiles clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_MOBILES, xdr_void, argp, xdr_liste_mobiles, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

mobile *
get_mobile_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static mobile clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_MOBILE, xdr_int, argp, xdr_mobile, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

boolean *
set_mobile_1(argp, clnt)
	params_set_mobile *argp;
	CLIENT *clnt;
{
	static boolean clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, SET_MOBILE, xdr_params_set_mobile, argp, xdr_boolean, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

liste_assurances *
get_assurances_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static liste_assurances clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_ASSURANCES, xdr_void, argp, xdr_liste_assurances, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

assurance *
get_assurance_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static assurance clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_ASSURANCE, xdr_int, argp, xdr_assurance, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

boolean *
set_assurance_1(argp, clnt)
	params_set_assurance *argp;
	CLIENT *clnt;
{
	static boolean clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, SET_ASSURANCE, xdr_params_set_assurance, argp, xdr_boolean, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

boolean *
set_adresse_livraison_1(argp, clnt)
	params_set_adresse *argp;
	CLIENT *clnt;
{
	static boolean clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, SET_ADRESSE_LIVRAISON, xdr_params_set_adresse, argp, xdr_boolean, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

liste_commandes *
get_commandes_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static liste_commandes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_COMMANDES, xdr_void, argp, xdr_liste_commandes, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

commande *
get_commande_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static commande clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, GET_COMMANDE, xdr_int, argp, xdr_commande, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

boolean *
valide_commande_1(argp, clnt)
	int *argp;
	CLIENT *clnt;
{
	static boolean clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, VALIDE_COMMANDE, xdr_int, argp, xdr_boolean, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

boolean *
set_date_livraison_1(argp, clnt)
	params_set_dl *argp;
	CLIENT *clnt;
{
	static boolean clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, SET_DATE_LIVRAISON, xdr_params_set_dl, argp, xdr_boolean, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
