/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "up2youService.h"

void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

liste_clients *
get_clients_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_clients  result;

	/*
	 * insert server code here
	 */

	return &result;
}

client *
get_client_1_svc(int *argp, struct svc_req *rqstp)
{
	static client  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
creer_commande_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

liste_mobiles *
get_mobiles_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_mobiles  result;

	/*
	 * insert server code here
	 */

	return &result;
}

mobile *
get_mobile_1_svc(int *argp, struct svc_req *rqstp)
{
	static mobile  result;

	/*
	 * insert server code here
	 */

	return &result;
}

boolean *
set_mobile_1_svc(params_set_mobile *argp, struct svc_req *rqstp)
{
	static boolean  result;

	/*
	 * insert server code here
	 */

	return &result;
}

liste_assurances *
get_assurances_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_assurances  result;

	/*
	 * insert server code here
	 */

	return &result;
}

assurance *
get_assurance_1_svc(int *argp, struct svc_req *rqstp)
{
	static assurance  result;

	/*
	 * insert server code here
	 */

	return &result;
}

boolean *
set_assurance_1_svc(params_set_assurance *argp, struct svc_req *rqstp)
{
	static boolean  result;

	/*
	 * insert server code here
	 */

	return &result;
}

boolean *
set_adresse_livraison_1_svc(params_set_adresse *argp, struct svc_req *rqstp)
{
	static boolean  result;

	/*
	 * insert server code here
	 */

	return &result;
}

liste_commandes *
get_commandes_1_svc(void *argp, struct svc_req *rqstp)
{
	static liste_commandes  result;

	/*
	 * insert server code here
	 */

	return &result;
}

commande *
get_commande_1_svc(int *argp, struct svc_req *rqstp)
{
	static commande  result;

	/*
	 * insert server code here
	 */

	return &result;
}

boolean *
valide_commande_1_svc(int *argp, struct svc_req *rqstp)
{
	static boolean  result;

	/*
	 * insert server code here
	 */

	return &result;
}

boolean *
set_date_livraison_1_svc(params_set_dl *argp, struct svc_req *rqstp)
{
	static boolean  result;

	/*
	 * insert server code here
	 */

	return &result;
}
